### Get all notes
GET http://localhost:5085/api/note
Accept: application/json

### Create new note
POST http://localhost:5085/api/note
Content-Type: application/json

{
  "title": "First note",
  "content": "Lorem ipsum..."
}
