### Register new user
POST http://localhost:5085/api/auth/register
Content-Type: application/json

{
  "username": "test1",
  "email": "test1@test.com",
  "password": "StrongPassword123!"
}

### Login user
POST http://localhost:5085/api/auth/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "StrongPassword123!"
}
